# Makefile for chapter 1, problem 1: Unique Snowflakes.
# From "Algorithmic Thinking" by Daniel Zingaro.

SRC = snowflakes.c
CC = gcc
CFLAGS = -w #supress warnings
LFLAGS = 
OUT = snowflakes

all	:	$(SRC)
	$(CC) $(SRC) $(CFLAGS) $(LFLAGS) -o $(OUT)

