# minimum makefile for sdl-demo-04 project.
SRC = demo04.cpp engine_zero.cpp engine_zero.h
CC = g++
CFLAGS = -w #no warnings
LFLAGS = -lSDL2 -lSDL2_image
OUT = demo04

all : $(SRC)
	$(CC) $(SRC) $(CFLAGS) $(LFLAGS) -o $(OUT)