# MAKEFILE-TEMPLATE
# -----------------
# A template for creating makefiles for C/Cpp projects.
# Uses gcc with no special compiler/linker flags.

SRC = dechex.cpp
OUT = dechex
COMPILER = g++
CFLAGS = -w
LFLAGS = 

all : $(SRC)
	$(COMPILER) $(SRC) $(CFLAGS) $(LFLAGS) -o $(OUT)
