# Makefile for solution to "Food Lines" problem from "Algorithmic Thinking."

SRC = foodlines.c
CC = gcc
CFLAGS = -w #suppress warnings
LFLAGS = 
OUT = foodlines

all : $(SRC)
	$(CC) $(SRC) $(CFLAGS) $(LFLAGS) -o $(OUT)

