# Project: sfml1

SRC = sfml1.cpp
OUT = sfml1
COMPILER = g++
CFLAGS = -w #suppress warnings
LFLAGS = -lsfml-graphics -lsfml-window -lsfml-system

all : $(SRC)
	$(COMPILER) $(SRC) $(CFLAGS) $(LFLAGS) -o $(OUT)
