/*******************************************************************************
	ProjectEuler.net - https://projecteuler.net/problem=2
	"Each new term in the Fibonacci sequence is generated by adding the
	previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms."
*******************************************************************************/
#include <iostream>

int FibR(int SeqNum){
    if(SeqNum <= 1) return 1;
    else return FibR(SeqNum-1) + FibR(SeqNum-2);
}

int main(int argc,char* argv[]){
    const nMax = 
    return 0;
}
/*
int main(int argc,char* argv[]){
    std::cout << "Prints a number in the Fibonacci number sequence." << std::endl;
    int userEntry = 1;
    while(userEntry){
        std::cout << "Enter: ";
        std::cin >> userEntry;
        std::cout << FibR(userEntry) << std::endl;
    }
    return 0;
}
*/