/******************************************************************************
	Project Euler - Problem 2

	From:
	ProjectEuler.net - https://projecteuler.net/problem=2
	"Each new term in the Fibonacci sequence is generated by adding the
	previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms."

	Done on the laptop downstairs and now here.
	Answer: 4613732
	Verified; correct.
******************************************************************************/
#include <iostream>

#define CEILING 4000000

int main(int argc, char* argv[])
{
	std::cout << "Fibonacci #'s below 4 million..." << std::endl;

	int llnum1 = 0;
	int llnum2 = 1;
	int llsum = 0;
	int llevensum = 0;

	bool b4mil = false;

	while (!b4mil)
	{
		llsum = llnum1 + llnum2;
		llnum1 = llnum2;
		llnum2 = llsum;

		if (llsum % 2 == 0)
			llevensum += llsum;

		if (llsum >= CEILING){
			b4mil = true;
			break;
		}

		std::cout << llsum << std::endl;
	}

    std::cout << "Whole Sum: " << llsum << std::endl;
	std::cout << "Sum of Evens: " << llevensum << std::endl;

	//keep console open until user presses a key.
	std::cin.get();
	return 0;
}
